### Read Flavors
GET http://localhost:8080/flavors HTTP/1.1

### Read Toppings
GET http://localhost:8080/toppings HTTP/1.1

### GET One topping
GET http://localhost:8080/toppings/65392c00eafb9a87e73a6d13 HTTP/1.1

### Delete Flavor
DELETE http://localhost:8080/flavors/6539e41decd86233be87a6a8 HTTP/1.1

### Delete Topping
DELETE http://localhost:8080/toppings/65397bb77f292433fef2878f HTTP/1.1

### POST Create flavor
POST http://localhost:8080/flavors HTTP/1.1
content-type: application/json 

{
    "flavor": "Vanilla",
    "brand" : "Blue bell",
    "type": "ice cream",
    "quantity" : "one pint",
    "price" : "6.10"
}


### POST Create topping
POST http://localhost:8080/toppings HTTP/1.1
content-type: application/json 

{
    "name": "Dulce de Leche",
    "type": "sauce"
}


### Render Flavors
GET http://api-icecreamshop.onrender.com/flavors HTTP/1.1