### Read Flavors
GET http://localhost:8080/flavors HTTP/1.1
### Read Toppings
GET http://localhost:8080/toppings HTTP/1.1

### Delete Flavor
DELETE http://localhost:8080/flavors/652e9d76ccea4712fcde067f HTTP/1.1


### POST Create flavor
POST http://localhost:8080/flavors HTTP/1.1
content-type: application/json 

{
    "flavor": "Vanilla",
    "brand" : "Blue bell",
    "type": "ice cream",
    "quantity" : "one pint",
    "price" : "6.10"
}


### POST Create topping
POST http://localhost:8080/toppings HTTP/1.1
content-type: application/json 
### content-type goes below POST line

{
    "name": "Cookie crumbs",
    "type": "cookie"
}


### Render Flavors
GET http://api-icecreamshop.onrender.com/flavors HTTP/1.1

### Render Toppings
GET http://api-icecreamshop.onrender.com/toppings HTTP/1.1

### Api Docs deployed in Render
GET http://api-icecreamshop.onrender.com/api-docs HTTP/1.1